# Generated by Django 2.1.7 on 2019-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20190317_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
