# Generated by Django 2.1.7 on 2019-03-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20190319_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
